apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: prometheus-network-policy
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "remote-agent.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app: prometheus
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - ports:
        - port: 9090
          protocol: TCP
        - port: 10901
          protocol: TCP
        - port: 10902
          protocol: TCP
  egress:
    - {}
{{- if .Values.otelCollector.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: otel-collector-network-policy
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "remote-agent.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app: otel-collector
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - ports:
        - port: 4317
          protocol: TCP
        - port: 4318
          protocol: TCP
        - port: 14250
          protocol: TCP
        - port: 14268
          protocol: TCP
        - port: 9411
          protocol: TCP
        - port: 13133
          protocol: TCP
  egress:
    - {}
{{- end }}
