{{- if .Values.otelCollector.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "remote-agent.labels" . | nindent 4 }}
    app: otel-collector
data:
  config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
      zipkin:
        endpoint: 0.0.0.0:9411
      jaeger:
        protocols:
          grpc:
            endpoint: 0.0.0.0:14250
          thrift_http:
            endpoint: 0.0.0.0:14268

    processors:
      batch:
        send_batch_size: 10000
        timeout: 5s
      memory_limiter:
        check_interval: 5s
        limit_mib: {{ .Values.otelCollector.resources.limits.memory | trimSuffix "Mi" | trimSuffix "Gi" | default "512" }}
        spike_limit_mib: 128
      resource:
        attributes:
          - key: cluster
            value: {{ .Values.cluster.name | quote }}
            action: upsert
          - key: environment
            value: {{ .Values.cluster.environment | quote }}
            action: upsert

    exporters:
      otlp:
        endpoint: {{ .Values.centralStack.otelEndpoint | quote }}
        tls:
          insecure: {{ .Values.otelCollector.tls.insecure | default true }}

    extensions:
      health_check:
        endpoint: 0.0.0.0:13133

    service:
      extensions: [health_check]
      pipelines:
        traces:
          receivers: [otlp, zipkin, jaeger]
          processors: [memory_limiter, resource, batch]
          exporters: [otlp]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: otel-collector
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "remote-agent.labels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "remote-agent.labels" . | nindent 4 }}
    app: otel-collector
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8889"
spec:
  type: {{ .Values.otelCollector.service.type | default "ClusterIP" }}
  ports:
    - name: otlp-grpc
      port: 4317
      targetPort: 4317
      protocol: TCP
    - name: otlp-http
      port: 4318
      targetPort: 4318
      protocol: TCP
    - name: jaeger-grpc
      port: 14250
      targetPort: 14250
      protocol: TCP
    - name: jaeger-thrift
      port: 14268
      targetPort: 14268
      protocol: TCP
    - name: zipkin
      port: 9411
      targetPort: 9411
      protocol: TCP
    - name: healthcheck
      port: 13133
      targetPort: 13133
      protocol: TCP
  selector:
    app: otel-collector
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "remote-agent.labels" . | nindent 4 }}
    app: otel-collector
spec:
  replicas: {{ .Values.otelCollector.replicas | default 1 }}
  selector:
    matchLabels:
      app: otel-collector
  template:
    metadata:
      labels:
        app: otel-collector
      annotations:
        checksum/config: {{ .Values.otelCollector | toYaml | sha256sum }}
    spec:
      serviceAccountName: otel-collector
      containers:
        - name: otel-collector
          image: {{ .Values.otelCollector.image.repository }}:{{ .Values.otelCollector.image.tag }}
          args:
            - "--config=/etc/otel/config.yaml"
          ports:
            - containerPort: 4317
              name: otlp-grpc
            - containerPort: 4318
              name: otlp-http
            - containerPort: 14250
              name: jaeger-grpc
            - containerPort: 14268
              name: jaeger-thrift
            - containerPort: 9411
              name: zipkin
            - containerPort: 13133
              name: healthcheck
          readinessProbe:
            httpGet:
              path: /
              port: 13133
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 13133
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            {{- toYaml .Values.otelCollector.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /etc/otel
      volumes:
        - name: config
          configMap:
            name: otel-collector-config
{{- end }}
