apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: prometheus-pdb
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "remote-agent.labels" . | nindent 4 }}
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: prometheus
{{- if .Values.otelCollector.enabled }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: otel-collector-pdb
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "remote-agent.labels" . | nindent 4 }}
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: otel-collector
{{- end }}
