apiVersion: v2
name: observability-remote-agent
description: Remote cluster agent — Prometheus + Thanos Sidecar + Promtail + OTel Collector
version: 0.1.0
appVersion: "1.0.0"
type: application

dependencies:
  - name: promtail
    version: "6.15.5"
    repository: "https://grafana.github.io/helm-charts"
    condition: promtail.enabled
